minimum_pre_commit_version: 4.2.0

ci:
  autoupdate_commit_msg: "chore(pre-commit): autoupdate"

repos:
  # Multi

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # General
      - id: check-added-large-files
        args: [--enforce-all]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
        exclude: ^python_app/{{ cookiecutter.dash_name }}/MERGE_PYTHON_APP.pyproject.toml$
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
      - id: trailing-whitespace

  - repo: https://github.com/GideonBear/pre-commit-hooks
    rev: v3.0.0
    hooks:
      # General
      - id: pre-commit-ci-skip
      # Gha
      - id: gha-pin
      # Shell
      - id: shfuncdecfmt
      - id: set-euo-pipefail
      # General - post
      - id: pre-commit-config-fmt

  # General

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--write-changes]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  # For .github/renovate.json5
  - repo: https://github.com/whtsky/pre-commit-pretty-format-json5
    rev: 1.0.0
    hooks:
      - id: pretty-format-json5
        args: [--indent=4, --no-sort-keys]

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-toc

  # Gha

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
        args: [--persona=auditor]
        exclude: ^.github/workflows/release.yml$
      - id: zizmor
        alias: zizmor-fix
        stages: [manual]
        args: [--persona=auditor, --fix=all]
        exclude: ^.github/workflows/release.yml$|^python/{{ cookiecutter.dash_name }}/.github/workflows/release.yml$

  # Shell

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["-e", "SC1083"]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [--write, --simplify, --indent=4]
