repos:
  - repo: https://github.com/GideonBear/pre-commit-hooks
    hooks:
      # Shell
      - id: shfuncdecfmt
      - id: set-euo-pipefail

  # Shell

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [--external-sources]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [--write, --simplify, --indent=4]
